[build]
functions = "netlify/functions"

[[redirects]]
from = "/thanks/:site/:age"
to = "/.netlify/builders/thanks"
status = 200
force = true
_generated_by_eleventy_serverless = "thanks"

[[redirects]]
from = "/thanks/:site"
to = "/.netlify/builders/thanks"
status = 200
force = true
_generated_by_eleventy_serverless = "thanks"

[[redirects]]
from = "/thanks/*"
to = "/.netlify/functions/thanks"
status = 200

[functions]
node_bundler = "zisi"
external_node_modules = [ "chrome-aws-lambda" ]

[[plugins]]
package = "./netlify/plugins/airtable-feed/index.js"

  [plugins.inputs]
  dataDir = "_data"
