[build]
functions = "netlify/functions"

[[redirects]]
from = "/thanks/*"
to = "/.netlify/functions/share"
status = 200
force = true

[functions]
node_bundler = "zisi"

[[redirects]]
from = "/thanks/:site/:age"
to = "/.netlify/builders/thanks"
status = 200
force = true
_generated_by_eleventy_serverless = "thanks"

[[plugins]]
  package = "./netlify/plugins/airtable-feed/index.js"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataDir = "_data"