[build]
functions = "netlify/functions"

[[redirects]]
from = "/thanks/*"
to = "/.netlify/functions/share"
status = 200
force = true

[functions]
node_bundler = "esbuild"
external_node_modules = [ "chrome-aws-lambda" ]
